language: node_js
node_js:
  - 10

before_script:
  - npm install -g bower
  - bower install

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/


scripts : 
  - vows --spec

notifications:
  email:
    recipients:
    - walterplatnumz@gmail.com
    on_success: change
    on_failure: always