# env:
#     global: CC_TEST_REPORTER_ID=032731043b33937655767fca3c9ecd15eec4b215ad4e6dd1b19280cd5ac29c6a

language: node_js

node_js:
    - 'stable'

# addons:
#     code_climate:
#         repo_token: '032731043b33937655767fca3c9ecd15eec4b215ad4e6dd1b19280cd5ac29c6a'

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/

# before_install:
#     - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#     - chmod +x ./cc-test-reporter

# before_script:
#     - npm install
#     - npm install nyc -g
#     - chmod +x ./cc-test-reporter
#     - ./cc-test-reporter before-build

# scripts:
#     # - npm run test
#     - nyc --reporter=lcov npm run test

# after_script:
#     - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    - CC_TEST_REPORTER_ID='032731043b33937655767fca3c9ecd15eec4b215ad4e6dd1b19280cd5ac29c6a'

before_script:
  - npm install nyc -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
    email:
        recipients:
            - walterplatnumz@gmail.com
        on_success: change
        on_failure: always
