language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

scripts : 
  - npm run test

notifications:
  email:
    recipients:
    - walterplatnumz@gmail.com
    on_success: change
    on_failure: always