env:
    global: CC_TEST_REPORTER_ID=0335aa593ff1f9e05d61351ad8dee7b3bdc43701e92a2ae4bc03751e33f0c82c

language: node_js
node_js:
    - 'stable'

addons:
    code_climate:
        repo_token: 0335aa593ff1f9e05d61351ad8dee7b3bdc43701e92a2ae4bc03751e33f0c82c

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/

before_install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

before_script:
    - npm install
    - npm install nyc -g
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - npm install codeclimate-test-reporter istanbul -g

scripts:
    - npm run test
    - nyc --reporter=lcov npm run test
    - istanbul cover node_modules/mocha/bin/_mocha -- -R spec

after_script:
    - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
    - codeclimate-test-reporter < ./coverage/lcov.info

notifications:
    email:
        recipients:
            - walterplatnumz@gmail.com
        on_success: change
        on_failure: always
